name: PR Reminder

on:
  schedule:
    - cron: "0 6 * * 6" # 매주 토요일 15:00 (UTC 기준으로 06:00)
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment variables
        run: |
          echo "DISCORD_CHANNEL_ID_PR=${{ secrets.DISCORD_CHANNEL_ID_PR}}"
          echo "REMINDER_BOT_TOKEN=${{ secrets.REMINDER_BOT_TOKEN }}"

      - name: Notify PR Due Date
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bot ${{ secrets.REMINDER_BOT_TOKEN }}" \
          -d "{\"content\": \"오늘은 토요일~ PR 제출하는 날입니다. 잊지 말고 문제 푼 거 올려주세요~!\"}" \
          https://discord.com/api/v10/channels/${{ secrets.DISCORD_CHANNEL_ID_PR }}/messages)
          echo "Response: $RESPONSE"
